### ISSUE TITLE
[BUG] Project Name limited to 22 characters

### ISSUE THREAD

**Issue by dfuentes87** [Wake-Tech-Programming-Club/wtpc-bot#9]
**Describe the bug:**
When adding a /project, the Name is limited to a maximum of 22 characters. Attempting to add more will result in error which is verbose in the Heroku log:

2022-04-09T18:11:12.724022+00:00 app[Worker.1]: error: value too long for type character varying(22)
2022-04-09T18:11:12.724032+00:00 app[Worker.1]: at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
2022-04-09T18:11:12.724033+00:00 app[Worker.1]: at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
2022-04-09T18:11:12.724034+00:00 app[Worker.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
2022-04-09T18:11:12.724034+00:00 app[Worker.1]: at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2022-04-09T18:11:12.724035+00:00 app[Worker.1]: at TLSSocket.emit (node:events:526:28)
2022-04-09T18:11:12.724035+00:00 app[Worker.1]: at addChunk (node:internal/streams/readable:315:12)
2022-04-09T18:11:12.724035+00:00 app[Worker.1]: at readableAddChunk (node:internal/streams/readable:289:9)
2022-04-09T18:11:12.724036+00:00 app[Worker.1]: at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
2022-04-09T18:11:12.724036+00:00 app[Worker.1]: at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
2022-04-09T18:11:12.724037+00:00 app[Worker.1]: length: 98,
2022-04-09T18:11:12.724038+00:00 app[Worker.1]: severity: 'ERROR',
2022-04-09T18:11:12.724038+00:00 app[Worker.1]: code: '22001',
2022-04-09T18:11:12.724038+00:00 app[Worker.1]: detail: undefined,
2022-04-09T18:11:12.724039+00:00 app[Worker.1]: hint: undefined,
2022-04-09T18:11:12.724039+00:00 app[Worker.1]: position: undefined,
2022-04-09T18:11:12.724040+00:00 app[Worker.1]: internalPosition: undefined,
2022-04-09T18:11:12.724040+00:00 app[Worker.1]: internalQuery: undefined,
2022-04-09T18:11:12.724040+00:00 app[Worker.1]: where: undefined,
2022-04-09T18:11:12.724041+00:00 app[Worker.1]: schema: undefined,
2022-04-09T18:11:12.724041+00:00 app[Worker.1]: table: undefined,
2022-04-09T18:11:12.724041+00:00 app[Worker.1]: column: undefined,
2022-04-09T18:11:12.724041+00:00 app[Worker.1]: dataType: undefined,
2022-04-09T18:11:12.724042+00:00 app[Worker.1]: constraint: undefined,
2022-04-09T18:11:12.724042+00:00 app[Worker.1]: file: 'varchar.c',
2022-04-09T18:11:12.724042+00:00 app[Worker.1]: line: '632',
2022-04-09T18:11:12.724042+00:00 app[Worker.1]: routine: 'varchar'
2022-04-09T18:11:12.724043+00:00 app[Worker.1]: }

**To Reproduce Steps to reproduce the behavior:**
1. Attempt to add project using, `/project add`
2. Use a Name for the project that is > 22 characters

**Expected behavior:**
Project name should be _reasonably_ longer. I would say up to 40 characters, no reason to make it too long.
For example, a reasonable name I was trying to use was "Programming Club Website".

**Screenshots**
Posted error above

**Device/Software (please complete the following information):**
n/a

**Additional context:**
None

**Comment by aahmad4** [comment]
Updated `projects` table schema as follows with these commands
```
                                Table "public.projects"
   Column    |          Type          | Collation | Nullable |         Default         
-------------+------------------------+-----------+----------+-------------------------
 id          | smallint               |           |          | 
 name        | character varying(50)  |           |          | NULL::character varying
 contact     | character varying(47)  |           |          | NULL::character varying
 description | character varying(250) |           |          | NULL::character varying
 createdat   | character varying(10)  |           |          | NULL::character varying
 updatedat   | character varying(10)  |           |          | NULL::character varying
```

```sql
ALTER TABLE projects ALTER COLUMN name TYPE varchar(50);
ALTER TABLE projects ALTER COLUMN description TYPE varchar(250);
```
